name: Atualizar estatísticas do perfil

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  gerar-estatisticas:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Gerar os cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: Rafael-FullDev
          BRANCH_NAME: main
          UTC_OFFSET: -3
          AUTO_PUSH: true
          THEME: tokyonight
